---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "frontend-app"
  namespace: "default"
  labels:
    app: "frontend-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend-app"
  template:
    metadata:
      labels:
        app: "frontend-app"
    spec:
      containers:
      - name: "frontend-app"
        image: "asia-south1-docker.pkg.dev/capable-matrix-441709-b0/artifactregistryattendance/frontend:latest"
        env:
            - name: REACT_APP_API_URL
              value: "http://34.8.183.235"
        resources:
          requests:
            cpu: "500m"         # Requesting 0.5 core
            memory: "512Mi"     # Requesting 512 MB of RAM
          limits:
            cpu: "1000m"        # Limiting to 1 core
            memory: "1024Mi"    # Limiting to 1 GB of RAM
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "frontend-app"
  namespace: "default"
  labels:
    app: "frontend-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "frontend-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3                # Allow scaling up to 3 replicas
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: Utilization
        averageUtilization: 60  # Scale based on 60% CPU utilization
  - type: "Resource"
    resource:
      name: "memory"
      target:
        type: Utilization
        averageUtilization: 60  # Scale based on 60% Memory utilization
