apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: frontend-app
  name: frontend-app
  namespace: app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "practice-app"  
spec:
  tls:
  - secretName: learning2024
  rules:
  - host: app-app.extramarks.com
  - http:
      paths:
      - backend:
          service:
            name: frontend-app-service
            port:
              number: 5000
        path: /
        pathType: Prefix
